version: '3.3'

services:
  webserver:
    build: .
    ports:
      - "9001:80"
    links:
      - mysql:mysql
    restart: always
    volumes:
      - ./html:/var/www/html/
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    # platform: linux/x86_64 -> m1노트북용 옵션
    environment:
      MYSQL_ROOT_PASSWORD: 'rootsemin'
      MYSQL_USER: 'you889'
      MYSQL_PASSWORD: 'semin'
      MYSQL_DATABASE: 'you889db'
    volumes:
      - ./data:/var/lib/mysql
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      - "52000:3306"

